class CreateCompanies < ActiveRecord::Migration
  def self.up
    create_table :companies do |t|
      t.string :name
      t.string :abbr
      t.integer :jobcount

      t.timestamps
    end
			  add_index :companies, :name, :unique => true
			  add_index :companies, :abbr, :unique => true
  end
  def self.down
    drop_table :companies
  end
end

#  --> Original autogenerated text:
#  def change
#    create_table :companies do |t|
#      t.string :name
#      t.string :abbr
#      t.integer :jobcount

#      t.timestamps
#    end
#  end
